### ISSUE TITLE
week 2 ideas  (cake)

### ISSUE THREAD

**Issue by spacemaine** [kk5dire/radiofnfthing#4]
uuhhhh i don't actually have any other than it should be the portal cake

**Comment by kk5dire** [comment]
#3 Reference 
@spacemain-is-awesome
spacemain-is-awesome
1 hour ago
make week 2 a cake lmao

23 replies
@kk5dire
kk5dire
1 hour ago
Maintainer
Author
can you include

Characters
music
bpm dif
etc helps lol
@spacemain-is-awesome
spacemain-is-awesome
1 hour ago
make week 2 cake with portal 2 music

@kk5dire
kk5dire
1 hour ago
Maintainer
Author
@spacemain-is-awesome can you give specific tracks please and this would be in this mod correct lol

@spacemain-is-awesome
spacemain-is-awesome
1 hour ago
https://www.youtube.com/watch?v=dT07bexTkak&list=PLC32EFD96F3E72D4E&index=30

@Sammie6789
This comment was marked as off-topic.
Show comment
@spacemain-is-awesome
spacemain-is-awesome
1 hour ago
actually this better https://www.youtube.com/watch?v=u9AyaFphAAU

@kk5dire
kk5dire
1 hour ago
Maintainer
Author
https://www.youtube.com/watch?v=dT07bexTkak&list=PLC32EFD96F3E72D4E&index=30

can you give me more specific tracks one for each song in game and a specific asset that you want used for the cake, and if you want any menu/bar assets you want done etc (optional)

@spacemain-is-awesome
spacemain-is-awesome
1 hour ago
i want those 2 on week 2, also this is a shitpost mod so why you being so specific

@Sammie6789
This comment was marked as off-topic.
Show comment
@spacemain-is-awesome
spacemain-is-awesome
1 hour ago
https://www.youtube.com/watch?v=dT07bexTkak&list=PLC32EFD96F3E72D4E&index=30

can you give me more specific tracks one for each song in game and a specific asset that you want used for the cake, and if you want any menu/bar assets you want done etc (optional)

it's a portal 2 thing

@kk5dire
kk5dire
1 hour ago
Maintainer
Author
i just mean as in their are multiple songs (easier to have multiple known songs for them) and asset wise same thing maskes it easier and to make sure its as wanted lol , if you really want i could go on google look up portal cake and portal music and call it a day :shipit:

@Sammie6789
This comment was marked as spam.
Show comment
@spacemain-is-awesome
spacemain-is-awesome
1 hour ago
i just mean as in their are multiple songs (easier to have multiple known songs for them) and asset wise same thing maskes it easier and to make sure its as wanted lol , if you really want i could go on google look up portal cake and portal music and call it a day :shipit:

https://www.pngjoy.com/preview/e7f4k2u5h3y1a3_portal-cake-team-fortress-2-cake-hd-png/

@kk5dire
kk5dire
43 minutes ago
Maintainer
Author
i just mean as in their are multiple songs (easier to have multiple known songs for them) and asset wise same thing maskes it easier and to make sure its as wanted lol , if you really want i could go on google look up portal cake and portal music and call it a day :shipit:

https://www.pngjoy.com/preview/e7f4k2u5h3y1a3_portal-cake-team-fortress-2-cake-hd-png/

i can work with that yes if thats all for assets, do you want me myself to choose a third song or do you have one in mind l :octocat:

@spacemain-is-awesome
spacemain-is-awesome
42 minutes ago
i just mean as in their are multiple songs (easier to have multiple known songs for them) and asset wise same thing maskes it easier and to make sure its as wanted lol , if you really want i could go on google look up portal cake and portal music and call it a day :shipit:

https://www.pngjoy.com/preview/e7f4k2u5h3y1a3_portal-cake-team-fortress-2-cake-hd-png/

i can work with that yes if thats all for assets, do you want me myself to choose a third song or do you have one in mind l :octocat:

week 2's 3rd song is unused so why lol

@Sammie6789
This comment was marked as spam.
Show comment
@Sammie6789
This comment was marked as off-topic.
Show comment
@Sammie6789
This comment was marked as disruptive content.
Show comment
@spacemain-is-awesome
This comment was marked as disruptive content.
Show comment
@Sammie6789
This comment was marked as disruptive content.
Show comment
@Sammie6789
This comment was marked as disruptive content.
Show comment
@kk5dire
kk5dire
21 minutes ago
Maintainer
Author
i just mean as in their are multiple songs (easier to have multiple known songs for them) and asset wise same thing maskes it easier and to make sure its as wanted lol , if you really want i could go on google look up portal cake and portal music and call it a day :shipit:

https://www.pngjoy.com/preview/e7f4k2u5h3y1a3_portal-cake-team-fortress-2-cake-hd-png/

i can work with that yes if thats all for assets, do you want me myself to choose a third song or do you have one in mind l :octocat:

week 2's 3rd song is unused so why lol

easter leg 💯

@kk5dire
kk5dire
9 minutes ago
Maintainer
Author
@spacemain-is-awesome should i have a super hard song in this one link before lol

**Comment by kk5dire** [comment]
@spacemain-is-awesome here is a good question, for the cake what should i do for differnt poses 

1.  differing images
2. stretch warp
3. perspective warp
4. distort warp
5.  something complete random and out of this world

**Comment by spacemain-is-awesome** [comment]
> @spacemain-is-awesome here is a good question, for the cake what should i do for differnt poses
> 
> 1. differing images
> 2. stretch warp
> 3. perspective warp
> 4. distort warp
> 5. something complete random and out of this world

yeah i guess

**Comment by spacemain-is-awesome** [comment]
i picture it somewhat like this, but then i realized you can't draw
![cake2](https://user-images.githubusercontent.com/83667024/117057038-477d8f80-ad1d-11eb-93d7-c225b07888fa.PNG)

**Comment by kk5dire** [comment]
> > @spacemain-is-awesome here is a good question, for the cake what should i do for differnt poses
> > 
> > 1. differing images
> > 2. stretch warp
> > 3. perspective warp
> > 4. distort warp
> > 5. something complete random and out of this world
> 
> yeah i guess

i asked a multiple choice question

**Comment by kk5dire** [comment]
> i picture it somewhat like this, but then i realized you can't draw
> ![cake2](https://user-images.githubusercontent.com/83667024/117057038-477d8f80-ad1d-11eb-93d7-c225b07888fa.PNG)

would depends on what style im going for, i most likely could not do a style to match the beauty of the other one

**Comment by spacemain-is-awesome** [comment]
> > > @spacemain-is-awesome here is a good question, for the cake what should i do for differnt poses
> > > 
> > > 1. differing images
> > > 2. stretch warp
> > > 3. perspective warp
> > > 4. distort warp
> > > 5. something complete random and out of this world
> > 
> > 
> > yeah i guess
> 
> i asked a multiple choice question

stretch warp or different images. sorry, i'm pretty hazy

**Comment by kk5dire** [comment]
@spacemain-is-awesome 
# ***done*** 
## check [Right Here](https://github.com/kk5dire/radiofnfthing/releases/tag/2.0)
